const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  ping: () => 'pong',

  getCompanyProfile: () => ipcRenderer.invoke('company:get'),
  getDashboardStats: () => ipcRenderer.invoke('dashboard:stats'),
  pickLogo: () => ipcRenderer.invoke('company:pickLogo'),
  saveCompanyProfile: (profile) => ipcRenderer.invoke('company:save', profile),

  listClients: () => ipcRenderer.invoke('clients:list'),
  getClient: (id) => ipcRenderer.invoke('clients:get', id),
  addClient: (client) => ipcRenderer.invoke('clients:add', client),
  updateClient: (id, client) => ipcRenderer.invoke('clients:update', id, client),
  tryDeleteClient: (id) => ipcRenderer.invoke('clients:tryDelete', id),
  archiveClient: (id) => ipcRenderer.invoke('clients:archive', id),
  listContacts: (clientId) => ipcRenderer.invoke('contacts:list', clientId),
  saveContacts: (clientId, contacts) => ipcRenderer.invoke('contacts:save', clientId, contacts),
  getClientOverview: (clientId) => ipcRenderer.invoke('clients:getOverview', clientId),
  listClientNotes: (clientId) => ipcRenderer.invoke('clients:listNotes', clientId),
  addClientNote: (clientId, text) => ipcRenderer.invoke('clients:addNote', clientId, text),
  updateClientNote: (noteId, text) => ipcRenderer.invoke('clients:updateNote', noteId, text),
  deleteClientNote: (noteId) => ipcRenderer.invoke('clients:deleteNote', noteId),


  listItems: () => ipcRenderer.invoke('items:list'),
  getItem: (id) => ipcRenderer.invoke('items:get', id),
  addItem: (item) => ipcRenderer.invoke('items:add', item),
  updateItem: (id, item) => ipcRenderer.invoke('items:update', id, item),
  deleteItem: (id) => ipcRenderer.invoke('items:delete', id),

  createQuote: (data, lineItems) => ipcRenderer.invoke('quotes:create', data, lineItems),
  updateQuote: (id, data, lineItems) => ipcRenderer.invoke('quotes:update', id, data, lineItems),
  listQuotes: () => ipcRenderer.invoke('quotes:list'),
  getQuote: (id) => ipcRenderer.invoke('quotes:get', id),
  getQuoteVersionHistory: (quoteId) => ipcRenderer.invoke('quotes:getVersionHistory', quoteId),
  setQuoteStatus: (id, status) => ipcRenderer.invoke('quotes:setStatus', id, status),
  markQuoteAccepted: (id, data) => ipcRenderer.invoke('quotes:markAccepted', id, data),
  markQuoteDeclined: (id, data) => ipcRenderer.invoke('quotes:markDeclined', id, data),
  exportQuotePdf: (quoteId) => ipcRenderer.invoke('quotes:exportPdf', quoteId),
  exportShareableQuoteHtml: (quoteId) => ipcRenderer.invoke('quotes:exportShareableHtml', quoteId),

  convertQuoteToInvoice: (quoteId, overrides) => ipcRenderer.invoke('invoices:convertFromQuote', quoteId, overrides),
  createFinalInvoiceFromDeposit: (depositInvoiceId, overrides) => ipcRenderer.invoke('invoices:createFinalFromDeposit', depositInvoiceId, overrides),
  getInvoiceByQuote: (quoteId) => ipcRenderer.invoke('invoices:getByQuote', quoteId),
  listInvoices: () => ipcRenderer.invoke('invoices:list'),
  getInvoice: (id) => ipcRenderer.invoke('invoices:get', id),
  exportInvoicePdf: (invoiceId) => ipcRenderer.invoke('invoices:exportPdf', invoiceId),
  setInvoiceStatus: (id, status) => ipcRenderer.invoke('invoices:setStatus', id, status),
  recordPayment: (id, payment) => ipcRenderer.invoke('invoices:recordPayment', id, payment),
  getInvoicePayments: (id) => ipcRenderer.invoke('invoices:payments', id),
  getPaymentMethods: () => ipcRenderer.invoke('invoices:methods'),
  getPaymentsReport: (filters) => ipcRenderer.invoke('reports:payments', filters),
  getProfitLossReport: (filter) => ipcRenderer.invoke('reports:profitLoss', filter),
  listExpenses: (filter) => ipcRenderer.invoke('expenses:list', filter),
  getExpense: (id) => ipcRenderer.invoke('expenses:get', id),
  createExpense: (data) => ipcRenderer.invoke('expenses:create', data),
  updateExpense: (id, data) => ipcRenderer.invoke('expenses:update', id, data),
  deleteExpense: (id) => ipcRenderer.invoke('expenses:delete', id),
  getExpensesSummary: (filter) => ipcRenderer.invoke('expenses:summary', filter),
  getExpenseCategories: () => ipcRenderer.invoke('expenses:categories'),
  issueCreditNote: (invoiceId, data) => ipcRenderer.invoke('creditNotes:issue', invoiceId, data),
  getCreditNotesForInvoice: (invoiceId) => ipcRenderer.invoke('creditNotes:forInvoice', invoiceId),
  getCreditNotesForClient: (clientId) => ipcRenderer.invoke('creditNotes:forClient', clientId),
  exportCreditNotePdf: (creditNoteId) => ipcRenderer.invoke('creditNotes:exportPdf', creditNoteId),
  getRecurringProfile: (invoiceId) => ipcRenderer.invoke('invoices:getRecurringProfile', invoiceId),
  setRecurringProfile: (invoiceId, data) => ipcRenderer.invoke('invoices:setRecurring', invoiceId, data),
  pauseRecurringProfile: (profileId) => ipcRenderer.invoke('invoices:pauseRecurring', profileId),
  resumeRecurringProfile: (profileId) => ipcRenderer.invoke('invoices:resumeRecurring', profileId),
  cancelRecurringProfile: (profileId) => ipcRenderer.invoke('invoices:cancelRecurring', profileId),
  triggerRecurringNow: (profileId) => ipcRenderer.invoke('invoices:triggerRecurringNow', profileId),
  checkDueRecurring: () => ipcRenderer.invoke('invoices:checkRecurringDue'),

  exportBackup: () => ipcRenderer.invoke('backup:export'),
  prepareRestore: () => ipcRenderer.invoke('backup:prepareRestore'),
  restoreBackup: (filePath) => ipcRenderer.invoke('backup:restore', filePath),

  getAutoBackupSettings: () => ipcRenderer.invoke('autobackup:getSettings'),
  saveAutoBackupSettings: (settings) => ipcRenderer.invoke('autobackup:saveSettings', settings),
  chooseAutoBackupFolder: () => ipcRenderer.invoke('autobackup:chooseFolder'),
  runAutoBackupNow: () => ipcRenderer.invoke('autobackup:runNow'),
  listAutoBackups: (folder) => ipcRenderer.invoke('autobackup:list', folder),

  getAuditEntries: (filter) => ipcRenderer.invoke('audit:getEntries', filter),

  getEmailSettings: () => ipcRenderer.invoke('email:getSettings'),
  saveEmailSettings: (settings) => ipcRenderer.invoke('email:saveSettings', settings),
  sendTestEmail: (recipient) => ipcRenderer.invoke('email:sendTest', recipient),
  sendDocumentEmail: (payload) => ipcRenderer.invoke('email:sendDocument', payload),
  getDocumentEmailLogs: (documentType, documentId) => ipcRenderer.invoke('email:getDocumentLogs', documentType, documentId),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),

  getReminderRules: () => ipcRenderer.invoke('reminders:getRules'),
  saveReminderRule: (rule) => ipcRenderer.invoke('reminders:saveRule', rule),
  deleteReminderRule: (id) => ipcRenderer.invoke('reminders:deleteRule', id),
  resetDefaultReminderRules: () => ipcRenderer.invoke('reminders:resetDefaults'),
  getReminderSettings: () => ipcRenderer.invoke('reminders:getSettings'),
  saveReminderSettings: (settings) => ipcRenderer.invoke('reminders:saveSettings', settings),
  getDueReminders: (referenceDate) => ipcRenderer.invoke('reminders:getDue', referenceDate),
  sendReminder: (payload) => ipcRenderer.invoke('reminders:send', payload),
  sendBatchReminders: (list) => ipcRenderer.invoke('reminders:sendBatch', list),
  checkAutoSendReminders: () => ipcRenderer.invoke('reminders:checkAutoSend'),
  getRevenueReport: (filter) => ipcRenderer.invoke('reports:revenue', filter),
  getClientProfitabilityReport: (filter) => ipcRenderer.invoke('reports:clientProfitability', filter),
  getAppLockSettings: () => ipcRenderer.invoke('lock:getSettings'),
  setAppLockPin: (payload) => ipcRenderer.invoke('lock:setPin', payload),
  verifyAppLockPin: (pin) => ipcRenderer.invoke('lock:verify', { pin }),
  disableAppLock: (currentPin) => ipcRenderer.invoke('lock:disable', { currentPin }),
});

